### ISSUE TITLE
Make Peek's pop-up window bigger?

### ISSUE THREAD

**Issue by richbordoni** [corbindavenport/peek#28]
Hi, is it possible to add a setting to make Peek's pop-up window bigger? Whether it's fit-to-screen, scaled, or fixed sizes, any one would be appreciated. It's currently a bit hard to see previews of documents and pdfs, etc. in the small window.

Thanks!

**Comment by corbindavenport** [comment]
This was a little hacky to implement, because the Tippy library (what Peek uses to generate the popups) isn't really designed for a custom fixed width and height, but I think I have it working okay. I've added a text box to the settings page for entering a custom preview width:

![image](https://user-images.githubusercontent.com/3879063/105621640-bb7fd180-5dd7-11eb-978b-a68c78701592.png)

Here's a .doc preview at 400px width (the previous default for documents was 320px wide and 280px tall):

![Screenshot from 2021-01-24 00-00-19](https://user-images.githubusercontent.com/3879063/105621616-7fe50780-5dd7-11eb-8178-ccf247f96025.png)

This is already live in the `dev` branch, and it will be in the next Peek update.
