### ISSUE TITLE
Open in new window / pop out

### ISSUE THREAD

**Issue by nicoleahmed** [corbindavenport/peek#49]
Hi Corbin
This is excellent work - haven't seen anything like it!
I have a few suggestions which I'll add separately. I'm using latest Google Chrome.

The preview window has options for "pop out" in the Google preview and "open in new window" in the MS preview.  These are currently blocked (or at least they are for me?).

It would be really useful to allow these links to open up the previews in a new page. Currently I use the "[Docs Online Viewer](https://chrome.google.com/webstore/detail/docs-online-viewer/gmpljdlgcdkljlppaekciacdmdlhfeon?hl=en)" extension for this. Or I use [Office editing for docs](https://chrome.google.com/webstore/detail/office-editing-for-docs-s/gbkeegbaiigmenfmjfclcdgdpimamgkj) to edit in the browser. 

Letting the links open to a full page would do away with the need for opening up external apps, or adding additional extensions.

**Comment by corbindavenport** [comment]
The pop-out button provided by Google is broken because of the sandboxing protection on frames. The next Peek update (which should be done sometime in the next month) will add a pop-out button on all previews, as seen in the below demo. 

The final interface might look a bit different but the functionality won't change. I'm just doing some optimizations for specific previews, and I'll add a toggle somewhere for opening the pop-outs in new windows or tabs for the existing window.


https://github.com/corbindavenport/peek/assets/3879063/fa026247-0e0d-4a0d-8f18-80fa626f6aec

**Comment by corbindavenport** [comment]
Peek 6.0 is now rolling out with this feature, closing.
